helm chart package handles over-long labels (#43)
* handle long branch names

* fix exit code

* tweak

* fix

diff --git a/.github/workflows/helm-chart-package.yml b/.github/workflows/helm-chart-package.yml
--- a/.github/workflows/helm-chart-package.yml
+++ b/.github/workflows/helm-chart-package.yml
@@ -89,6 +89,12 @@ jobs:
           echo "IMAGE_REPOSITORY=$IMAGE_REPOSITORY"
           echo "TAG=$TAG"
 
+          LABEL=$REPOSITORY-$TAG
+          if [[ "${#LABEL}" -gt 63 ]]; then
+            echo "::error::RFC 1123 Label Names maximum length of 63 characters reached for '$LABEL', suggest shortening your repository or branch name."
+            exit 1
+          fi
+
           printf "\n\n>helm version\n"
           helm version
 
